const questionsData = [
    "Of the people in this room, who is the most handsome?",
    "Of the people in this room, who is the prettiest?",
    "Name the most bad-tempered person in this room.",
    "When’s the last time you were flat-out rejected? How did you handle it?",
    "Of the people in this room, who is most likely to fail in life?",
    "Of the people in this room, who is most likely to remain single?",
    "Name the person with the worst fashion sense in this room.",
    "If you had to sleep with one person in this room, who would it be?",
    "Of the people in this room, who would you go on a date with?",
    "Who would you feel most comfortable with naked in this room?",
    "What’s the biggest secret you’ve ever kept from your parents?",
    "Name the ugliest person in this room.",
    "Who is the most judgmental in this room?",
    "What’s the biggest lie you’ve ever told without getting caught?",
    "Who do you most want to switch lives with and why in this room?",
    "Name the most egoistic person in this room.",
    "Of the people in this room, who do you disagree with most frequently?",
    "Name the most unreliable person in this room.",
    "If you could erase one past experience, what would it be?",
    "Name the most incompetent person in this room.",
    "What’s the wildest thing you’ve ever done to attract a crush?",
    "What’s the most flirtatious thing you’ve ever done?",
    "Who is the most hypocritical in this room?",
    "What three adjectives best describe your vagina/penis?",
    "Name the most stingy person in this room.",
    "Name one person you would remove from the clique.",
    "What did you think about the first (or last) time you masturbated?",
    "What’s the most surprising thing that’s ever turned you on?",
    "What’s the most awkward experience you’ve had with your crush?",
    "Of the people in this room, who do you consider the sluttiest?",
    "What’s the cruelest thing you’ve ever done to a friend?",
    "Name the most vain person in this room.",
    "How do you really feel about anal sex?",
    "What’s your favorite sex toy you have used?",
    "Who is the most spoiled in this room?",
    "What’s the biggest mistake you’ve ever made in bed?",
    "Who is the most irresponsible in this room?",
    "Most number of times you’ve ever masturbated within one week?",
    "Of the people in this room, who do you hate the most, and why?",
    "Name the person who is most likely to cheat in this room.",
    "What’s the biggest dating disappointment you’ve experienced so far?",
    "If you had to marry one person in this room, who would it be?",
    "Most embarrassing thing that your parents have caught you doing?",
    "If you had to cheat who would it be with?",
    "How old were you when you lost your virginity?",
    "Have you ever betrayed anyone in this room?",
    "Have you fallen in love with a friend of your partner?",
    "Name the most manipulative person in this room.",
    "Have you ever thought of cheating on your partner?",
    "Have you ever tried to take a sexy or naked picture of yourself?",
    "Who are you secretly attracted to?",
    "Name the most pretentious person in this room.",
    "How would you rate your looks on a scale of 1 to 10?",
    "Who is most difficult to please in this room?",
    "Name the most materialistic person in this room.",
    "Have you ever accidentally revealed a friends' secret?",
    "What is the worst date you’ve ever been on?",
    "Name the most immature person in this room.",
    "When was the last time you watched an adult movie? What was it?",
    "Would you marry someone for their money?",
    "Name the most gullible person in this room.",
    "Have you ever compromised your morals for money?",
    "How many people have you slept with?",
    "Why do you think we can't be more than friends?",
    "Name the most dishonest person in this room.",
    "Would you have sex on your first date?",
    "Of the people in the room, who do you trust the least?",
    "What is more important to you, revenge or forgiveness?",
    "Name the most horny person in this room.",
    "What is something you feel guilty about?",
    "Have you ever had a one night stand? With who?",
    "Who has the best ass here?",
    "Name the most boring person in this room.",
    "What are you most self-conscious about?",
    "What do most people think is true about you, but isn’t?",
    "What is something your friends would never expect that you do?",
    "Why did you break up with your last boyfriend or girlfriend?",
    "What is something that you have never told anyone?",
    "Tell me something you don’t want me to know.",
    "How many hearts have you broken before?",
    "Name the most anti-social in this room.",
    "What's your guiltiest pleasure?",
    "Have you ever received oral sex?",
    "Name the most unloyal person in this room.",
    "Have you ever been cheated on? By who?",
    "What habit can’t you seem to quit?",
    "How many people have you kissed?",
    "Would you cheat on your partner if they said it was okay?",
    "Name the most selfish person in this room.",
    "Would you donate an organ to someone in this room?",
    "Have you ever spread a rumor?",
    "What is your biggest insecurity?",
    "Name one bad personality trait of each person in the room.",
    "How many times have you masturbated today?",
    "Who is your favourite pornstar?",
    "Have you ever been tempted to cheat on someone?",
    "How many times have you ever masturbated in a day?",
    "What is your greatest fetish?",
    "Who is the most cowardly in this room?",
    "Name one person who complain the most in this room?",
    "Do you masturbate?",
    "What is your favourite category of porn?",
    "Have you ever given oral sex?",
    "Longest amount of time that you have gone without intercourse?",
    "Could you live without having sex for the rest of your life?",
    "Name one thing on your bucket list.",
    "What is your fondest memory?",
    "Longest amount of time you ever been away from home? And why?",
    "Have you ever had a crush on your colleague?",
    "Who are you most jealous of, and why?",
    "When’s the last time you apologized? What for?",
    "What’s the longest you’ve gone without showering?",
    "Are you a virgin?",
    "What is your greatest fear in a relationship?",
    "What’s your biggest regret in life?",
    "Do you still have feelings for any of your exes?",
    "Have you ever ghosted a date?",
    "Who is most likely to hold grudges in this room?",
    "When’s the last time you got dumped?",
    "Who are you the closest to in this room?",
    "Name one thing you’d change about every person in this room.",
    "What’s your deal breaker in a romantic relationship?",
    "Who was your first boyfriend/girlfriend?",
    "How long was your longest relationship? With who?",
    "What was your first heart break?",
    "Name the alpha male in this room.",
    "Do you secretly dislike anyone in this room?",
    "Have you ever said, 'I love you' and not really meant it? To whom?",
    "Have you ever had a crush on a friend’s girlfriend or boyfriend?",
    "Who do you not want to see naked here?",
    "Most embarrassing thing that has happened to you in public?",
    "Have you ever cheated on a test or an exam?",
    "What is your biggest pet peeve?",
    "Name one person you would unfriend in this room.",
    "What makes you laugh?",
    "What is something you find absolutely disgusting?",
    "How long can you last in bed usually?",
    "Do you masturbate to your female friends' photos?",
    "What do you like to do when you are alone?",
    "Doggy style or missionary position?",
    "Have you ever masturbated to local Instagram influencers?",
    "What is your favourite sex position?",
    "Which person's sister in this room would you hook up with?",
    "What is your favourite sex position?",
    "Who did you have your first kiss with?",
    "Spit or Swallow?",
    "Have you ever been in a serious relationship?",
    "Have you ever paid for sex?",
    "Where do you like to be touched?",
    "Name the person you would hang out the least in this room.",
    "How did you lose your virginity?",
    "Have you ever fantasized about anyone in this room?",
    "What are you like in bed?",
    "Virgin or non-virgin girl?",
    "Do you enjoy rough or slow sex?",
    "Does size matters to you?",
    "Tits or Ass?",
    "Would you ever do a threesome?",
    "Have you ever had a crush on your teacher in school?",
    "Who is the hottest teacher in <insert_name> school?",
    "Weirdest thing you have done when you're alone?",
    "<insert_three_names> Shoot.Shag.Marry.",
    "Juiciest clubbing story?",
    "Describe <insert_name> in one word.",
    "Describe your ideal type.",
    "Who are you the most awkward with in this room?",
    "Have you ever been jealous of <insert_name>?",
    "Who do you think is a better friend, <insert_name> or me?",
    "Who is the most attention-seeking in this room?",
    "Which part of your body are you most insecure about?",
    "How much money would it take to make out with <insert_name>?",
    "Who is most likely to be your long term friend in this room?",
    "Would you rather be a virgin forever or have sex with your sibling one time?",
    "Would you rather live forever or die in the next five minutes?",
    "Would you rather be an ugly genius or a hot idiot?",
    "Would you rather have sex with my best friend, or with your best friend?",
    "Would you rather give up sex or masturbating for a month?",
    "Would you rather be with someone who loves you more or with someone you love more?",
    "Would you rather be horny all the time or never be able to have an orgasm?",
    "Would you rather get a call from someone you slept with saying she has an STD or that she’s pregnant?",
    "Blowjob or handjob?",
    "Fingering or sex?",
    "Would you rather win $50,000 or let your best friend win $500,000?",
    "Would you rather know how you will die or when you will die?",
    "Would you rather forget how to speak or how to read?",
    "Would you rather have 5 failed marriages or never get married?",
    "Would you rather have many FWB or a partner who really loves you?",
    "Would you rather forget your partner’s birthday or your anniversary every year?",
    "Would you rather be the funniest or the smartest person in a room?",
    "Would you rather clean up someone else’s vomit or blood?",
    "Would you rather hear a comforting lie or an uncomfortable truth?",
    "Would you rather have fortune or fame?",
    "Would you rather be able to read minds or predict the future?",
    "Would you rather give your parents or your boss access to your browser history?",
    "Would you rather have your boss or your parents look through your text messages?",
    "Would you rather be the class clown or the teacher’s pet?",
    "Would you rather lose all of your teeth or all of your hair?",
    "Would you rather go blind or deaf?",
    "Would you rather die before or after your spouse?",
    "Would you rather be a feminine man or a masculine woman?",
    "Would you rather be always in debt or never be able to make more than $3,500 a month?",
    "Would you rather be feared by all or loved by all?",
    "Would you rather be held in high regard by your parents or your friends?",
    "Would you rather kill your best friend or your partner?",
    "What makes a person beautiful to you?",
    "What personality trait do you wish you had?",
    "Would you rather have more time or more money?",
    "Would you rather be too busy or too bored?",
    "Would you rather have many good friends or one very best friend?",
    "Would you rather be good-looking or have many friends?",
    "Would you rather be kind or loyal?",
    "Would you rather be caught cheating or catch me cheating?",
    "Would you rather know it all or have it all?",
    "Have you ever walked in on your parents doing it?",
    "What's the first thing you would do if you woke up one day as the opposite sex?",
    "Who is your secret crush?",
    "Do you think you'll marry your current girlfriend/boyfriend?",
    "What is the most illegal thing you have ever done?",
    "Who in this room would be the worst person to date? Why?",
    "What size is your bra?",
    "You win a trip and are allowed to bring two people. Who do you pick in this room?",
    "If you had to flash just one person in this room, who would it be?",
    "Who has the best smile in this room?",
    "Who here do you think would be the best kisser?",
    "Have you ever tried drugs?",
    "Do you have hidden piercings or tattoos?",
    "Who has seen you without clothes on?",
    "Have you ever sent a nude selfie? Who would you send it to?",
    "What's your ultimate sexual fantasy?",
    "Tell us about your first kiss.",
    "Have you ever taken a pregnancy test kit?",
    "Have you ever got arrested?",
    "Have you ever worn the same underwear two days in a row?",
    "What's the most useless talent you have?",
    "What makes you happy?",
    "Have you ever lied to your partner to avoid an intimate moment?",
    "What’s the dirtiest thought you’ve ever had?",
    "Have you ever considered being a pornstar?",
    "Have you ever made out with someone here?",
    "Have you ever lied on your resume to get a job?",
    "Have you ever practiced kissing in front of a mirror?",
    "Do you pick your nose when you’re alone?",
    "If someone offered you $1 million dollars to break up with your S/O, would you do it?",
    "Have you ever been caught checking someone out?",
    "Which part of your body are you ticklish?",
    "Where is the craziest place you have ever had sex?",
    "Have you ever won an award you didn’t deserve?",
    "Have you ever cheated on someone?",
    "Which is worse, physical pain or emotional pain?",
    "Have you ever had a near-death experience?",
    "What’s something you wish you were better at?",
    "What is the worst pain you’ve ever experienced?",
    "What is the best advice you have ever received?",
    "Have you ever smoked marijuana?",
    "Have you ever worn a G-string?",
    "Have you ever used a dildo?",
    "When was the last time you fingered yourself?",
    "Have you ever had a paranormal experience?",
    "Which local Instagram influencer have you fantasised before?",
    "When was the last time you shaved your pubes?",
    "Are you OK with your girlfriend doing a boob job?",
    "Have you ever considered doing a boob job?",
    "When was the last time you fingered yourself?",
    "When was the last time you visited a prostitute?",
    "What do you do when you get horny in public?",
    "Have you ever masturbated in a public bathroom?",
    "How would you dominate your boss sexually if given the chance?",
    "What’s your favorite way to be seduced?",
    "Who gave you your first orgasm?",
    "What kind of porn turns you on?",
    "Does naughty talk get you aroused?",
    "How long does it take you to get yourself off, on average?",
    "If you had to pick, would you be a dominatrix or a submissive?",
    "Have you ever sent nudes of yourself?",
    "Are you loud or quiet during sex?",
    "Have anyone seen you naked (accidentally)?",
    "Are you wearing a bra right now?",
    "How often do you masturbate?",
    "Fast and hard or slow and gentle?",
    "How often would you have sex if you could choose?",
    "Do you like BDSM?",
    "What is your biggest turn off?",
    "What is the best that a woman can feed you in bed?",
    "Will you ever have an orgy?",
    "Who will you do a threesome with in this room?",
    "If your boyfriend asks for a blowjob, would you give?",
    "What kind of parents do you think you will be?",
    "What do you do to get yourself sexy?",
    "Would you rather date a fuck boy or a guai kia?",
    "What is your driving force in life?",
    "What is your idea of the perfect marriage proposal?",
    "Who is most likely to marry for something other than love in this room?",
    "Who is most likely to go topless on the beach here?",
    "Who is most likely to have their nudes leaked here in this room?",
    "Who is most likely to forgive a cheating partner here?",
    "Who is most likely to stay in a toxic relationship here?",
    "Who is most likely to become a gold digger here?",
    "Who is most likely to be pregnant after a one-night stand here?",
    "Who is most likely to go on a blind date arranged by their mom here?",
    "Who is most likely to get punched in the face here?",
    "On a scale of 1 to 10, how would you rate your life right now?",
    "What's the most important thing to you in life?",
    "Name the person in the room who you think is the best dressed.",
    "What is the best gift anyone's ever given to you?",
    "Who do you admire the most here?",
    "Would you rather be known for your intelligence or your looks?",
    "Have you ever walked up and asked for a girl's contact number?",
    "Who is the cutest here?",
    "What is one thing you dislike about each person here?",
    "Have you ever asked someone out?",
    "What's the sexiest thing about a guy?",
    "What's the sexiest thing about a girl?",
    "Would you date someone shorter than you?",
    "What if your best friend told you that she liked your crush?",
    "Rate everyone in the room from 1 to 10, with 10 being the best personality.",
    "If your parents hate your girlfriend, would you dump her?",
    "If your girlfriend hates your best friend, what would you do?",
    "If you haven't had your first kiss yet, who in this room do you want to have your first kiss with?",
    "Who has the prettiest eyes here?",
    "Have you ever been in a 'friends with benefits' situation?",
    "Who here sings the best?",
    "Are you more of a leader or follower?",
    "How often do you think about sex?",
    "Have you ever had sex in a car?",
    "Who is your bestfriend?",
    "Do you find anyone in this room dateable?",
    "What was the most kinky thing you've ever done?",
    "What is your weirdest fetish?",
    "Will you consider FWB?",
    "Will you consider sex for grades in college?",
    "Have you ever been caught masturbating? By who?",
    "Do you regret joining <insert_event>?",
    "What is your worst habit?",
    "Who do you find good-looking in this room?",
    "Do you have a wank bank?",
    "Do you have porn videos in your phone or laptop right now?",
    "Are you into MILF porn?",
    "Are you straight?",
    "Have you ever considered looking for a sugar daddy/mummy?",
    "Have you ever had a sugar daddy/mummy?",
    "Have you ever hooked up with a prof in college?",
    "Have you ever seduced anyone?",
    "Have you ever being seduced?",
    "What is your favourite sport?",
    "If you could choose another name for yourself, what would it be?",
    "What would people be surprised to find out about you?",
    "What word do people use to describe you most often?",
    "Do you believe in talent or hard work more in achieving success?",
    "What do you take everywhere with you?",
    "What is one thing in your life that you couldn’t live without?",
    "How do you handle failure?",
    "When was the last time you used dating app to meet someone?",
    "What's your life's biggest dream?",
    "Are you an introvert or extrovert?",
    "What is one thing you love about yourself?",
    "Have you ever crushed on your best friend?",
    "If you had a talk show, who would your first three guests be?",
    "What is your first impression of everyone in this room?",
    "What do you think the secret to a good life is?",
    "What type of partner would you choose for yourself?",
    "What principles do you live your life by?",
    "What website or app doesn’t exist, but you really wish it did?",
    "How into self-improvement are you?",
    "What has really taken a toll on you?",
    "Would you rather have a handsome or rich boyfriend?",
    "Have you ever liked multiple person at once?",
    "Are you a morning or night person?",
    "What is your love language?",
    "What is the most important in a romantic relationship to you?",
    "Do you believe in marriage?",
    "Have you ever made out with someone just because you were horny at that time?",
    "What is your favorite way to spend a Saturday?",
    "Are you interested in Netflix and chill?",
    "Have you ever flirted with a stranger online?",
    "Do you like dirty talk?",
    "What’s one thing you’ve done, but will never end up doing again?",
    "Do you believe things happen for a reason? Why?",
    "On a scale of 1 to 10, how would you rate your blow job skill?",
    "Do you like to be punished while making love?",
    "Do you enjoy being fucked from behind?",
    "What are the things that stand between you and complete happiness?",
    "If you could go back in time, once, and change a single thing – what would it be?",
    "Who is that one person you text everyday?",
    "What makes you feel loved?",
    "How much do you judge a person by their appearance?",
    "What do you do when you're sad?",
    "How would you describe yourself in three words?",
    "What's your kind favorite kind of foreplay?",
    "What kind of sounds do you make during sex?",
    "What size of d**k would you prefer and enjoy?",
    "What makes you wet without fail?",
    "Be honest – when’s the last time you masturbated?",
    "How far can you go on a third date?",
    "Have you ever had sex with your ex after breaking up?",
    "Are you fine with your partner watching porn for self-pleasure?",
    "Are you the kind to initiate a confession?",
    "Do you prefer big parties or small gatherings?",
    "Is there anything unusual that you’re addicted to?",
    "Do you say yes or no more often in life?",
    "What is the most romantic trip you dream of going on?",
    "Do you prefer a good hug or a good kiss?",
    "How do you like a guy/girl to show his/her feelings?",
    "Do you believe in love at first sight?",
]

export default questionsData