const questionsData = [
    "Of the people in this room, who is the most handsome?",
    "Of the people in this room, who is the prettiest?",
    "When’s the last time you were flat-out rejected and how did you handle it?",
    "Of the people in this room, who is most likely to fail in life?",
    "Of the people in this room, who is most likely to remain single?",
    "If you had to sleep with one person in this room, who would it be?",
    "Of the people in this room, who would you go on a date with?",
    "Of the people in this room, who would you feel most comfortable with naked?",
    "What’s the biggest secret you’ve ever kept from your parents?",
    "What’s the biggest lie you’ve ever told without getting caught?",
    "Who do you most want to switch lives with and why in this room?",
    "Of the people in this room, who do you disagree with most frequently?",
    "If you could erase one past experience, what would it be?",
    "What’s the wildest thing you’ve ever done to attract a crush?",
    "What’s the most flirtatious thing you’ve ever done?",
    "What three adjectives best describe your vagina/penis?",
    "Of the people in this room, who do you want to remove from the clique?",
    "What did you think about the first (or last) time you masturbated?",
    "What’s the most surprising thing that’s ever turned you on?",
    "What’s the most awkward experience you’ve had with your crush?",
    "Of the people in this room, who do you consider the sluttiest?",
    "What’s the cruelest thing you’ve ever done to a friend?",
    "How do you really feel about anal sex?",
    "What’s your favorite sex toy you have used?",
    "What’s the biggest mistake you’ve ever made in bed?",
    "What’s the most number of times you’ve ever masturbated within one week?",
    "Of the people in this room, who do you hate the most, and why?",
    "What’s the biggest dating disappointment you’ve experienced so far?",
    "If you had to marry one person in this room, who would it be?",
    "What is the most embarrassing thing that your parents have caught you doing?",
    "If you had to cheat who would it be with?",
    "How old were you when you lost your virginity?",
    "Have you ever betrayed anyone in this room?",
    "Have you fallen in love with a friend of your partner?",
    "Have you ever thought of cheating on your boyfriend/girlfriend?",
    "Have you ever tried to take a sexy or naked picture of yourself?",
    "Who are you secretly attracted to?",
    "How would you rate your looks on a scale of 1 to 10?",
    "Have you ever accidentally revealed a friends secret?",
    "What is the worst date you’ve ever been on?",
    "When was the last time you watched an “adult movie”, and what is it?",
    "Would you marry someone for their money?",
    "Have you ever compromised your morals for money?",
    "How many people have you slept with?",
    "Why do you think we can't be more than friends?",
    "Would you have sex on your first date?",
    "Of the people in the room, who do you trust the least?",
    "What is more important to you, revenge or forgiveness?",
    "What is something you feel guilty about?",
    "Have you ever had a one night stand? With who?",
    "Who has the best ass here?",
    "What are you most self-conscious about?",
    "What do most people think is true about you, but isn’t?",
    "What is something your friends would never expect that you do?",
    "Why did you break up with your last boyfriend or girlfriend?",
    "What is something that you have never told anyone?",
    "Tell me something you don’t want me to know.",
    "How many hearts have you broken before?",
    "What's your guiltiest pleasure?",
    "Have you ever received oral sex?",
    "Have you ever been cheated on? By who?",
    "What habit can’t you seem to quit?",
    "How many people have you kissed?",
    "Would you cheat on your partner if they said it was okay?",
    "Would you donate an organ to someone in this room?",
    "Have you ever spread a rumor?",
    "What is your biggest insecurity?",
    "How many times have you masturbated today?",
    "Who is your favourite pornstar?",
    "Have you ever been tempted to cheat on someone?",
    "How many times have you ever masturbated in a day?",
    "What is your greatest fetish?",
    "Do you masturbate?",
    "What is your favourite category of porn?",
    "Have you ever given oral sex?",
    "Longest amount of time that you have gone without intercourse?",
    "Could you live without having sex for the rest of your life?",
    "Name one thing on your bucket list.",
    "What is your fondest memory?",
    "Longest amout of time you ever been away from home? And why?",
    "Have you ever had a crush on your colleague?",
    "Who are you most jealous of, and why?",
    "When’s the last time you apologized? What for?",
    "What’s the longest you’ve gone without showering?",
    "Are you a virgin?",
    "What is your greatest fear in a relationship?",
    "What’s your biggest regret in life?",
    "Do you still have feelings for any of your exes?",
    "Have you ever ghosted a date?",
    "When’s the last time you got dumped?",
    "Name one thing you’d change about every person in this room.",
    "What’s your deal breaker in a romantic relationship?",
    "Who was your first boyfriend/girlfriend?",
    "How long was your longest relationship? With who?",
    "What was your first heart break?",
    "Do you secretly dislike anyone in this room?",
    "Have you ever said, “I love you” and not really meant it? To whom?",
    "Have you ever had a crush on a friend’s girlfriend/boyfriend?",
    "Who do you not want to see naked?",
    "Most embarrassing thing that has happened to you in front of a crowd?",
    "Have you ever cheated on a test or an exam?",
    "What is your biggest pet peeve?",
    "What makes you laugh?",
    "What is something you find absolutely disgusting?",
    "How long can you last in bed usually?",
    "Do you masturbate to your female friends' photos?",
    "What do you like to do when you are alone?",
    "Have you masturbated to local Instagram influencers?",
    "What is your favourite sex position?",
    "Which person's sister in this room would you hook up with?",
    "What is your favourite sex position?",
    "Who did you have your first kiss with?",
    "Spit or Swallow?",
    "Have you ever been in a serious relationship?",
    "Have you ever paid for sex?",
    "Where do you like to be touched?",
    "How did you lose your virginity?",
    "Have you ever fantasized about anyone in this room?",
    "What are you like in bed?",
    "Do you enjoy rough or slow sex?",
    "Does size matters to you?",
    "Tits or Ass?",
    "Would you ever do a threesome?",

]

export default questionsData